### ISSUE TITLE
daily metrics from SfnData objects

### ISSUE THREAD

**Issue by rafapoyatos** [sapfluxnet/sapfluxnetr#1]
Ideally, a function (or sets of functions) to obtain daily metrics of sap flow and environmental data. Here I list a set of possible metrics:
- [x] Daily mean
- [x] Daily minimum
- [x] Daily N
- [x] Daily coverage (actual data present compared to total number of daily timesteps)
- [x] Midday mean (pass tmd1 and tmd2 as arguments in the function so it can be fine-tuned, but 11-13 by default)
- [x] Midday N
- [x] Predawn mean (pass tpd1 and tpd2 as arguments in the function so it can be fine-tuned, but 3-5 by default)
- [x] Time of Minimum
- [x] Time of Maximum
- [x] Quantiles (95, 99? maybe user-defined, supplied via function argument?)
- [x] Diurnal centroid for sapflow based on Jake's code

- [x] Similar mean and N metrics for nighttime values, but for these it may be a little more complicated as it would probably be better to define night for day 1 as, for example, 22:00 to 3:00 (day +1), and much better to define night in terms of solar angle (or extraterrestrial radiation, or whatever indicator we already have).

In my mind, this function is one to rule all daily aggregation metrics, so it would take the arguments:
- SfnData object
- time period for midday
- time period for predawn
- solar angle (or extraterrestrial radiation) thresholds for nighttime

**Comment by MalditoBarbudo** [comment]
@rafapoyatos That was fast!! :smile:
Working on it!

**Comment by MalditoBarbudo** [comment]
@rafapoyatos 
I have a doubt, when returning the daily metrics with nighttime, the metrics for nightime are those for the night, but the general metrics are for all the day, including the night, no? or do I need to filter the "day values" also?

**Comment by rafapoyatos** [comment]
@MalditoBarbudo @vflo 

Ideally, we would consider daily means (these include the night) and daytime means (so we exclude nightime values within a day).
For nightime it's a little bit more tricky because it wouldn't be as straightforward as daytime. For a given DOY, we should consider nighttime spanning DOY and DOY+1. At least it makes more sense to me, although there could also be an option to select for this. 
Ways to tackle the nighttime definition vary in the literature, and they are sometimes not even reported (I attach some papers).

- Dawson: they consider 22:30 to 4:30
- Forster: based on radiation threshold or sunrise/sunset timing (+/- 1 hour)
- Fisher: they don't report how nighttime is defined

[Fisher et al_2007_What the towers don't see at night.pdf](https://github.com/sapfluxnet/sapfluxnetr/files/1812085/Fisher.et.al_2007_What.the.towers.don.t.see.at.night.pdf)

[Forster_2014_How significant is nocturnal sap flow.pdf](https://github.com/sapfluxnet/sapfluxnetr/files/1812075/Forster_2014_How.significant.is.nocturnal.sap.flow.pdf)

[Dawson et al_2007_Nighttime transpiration in woody plants from contrasting ecosystems.pdf](https://github.com/sapfluxnet/sapfluxnetr/files/1812070/Dawson.et.al_2007_Nighttime.transpiration.in.woody.plants.from.contrasting.ecosystems.pdf)

**Comment by MalditoBarbudo** [comment]
@rafapoyatos @vflo 
Ok, for us by hours would be the easiest, like predawn and midday (it's pretty straightforward), but I can also implement the method by Forster based on radiation threshold and let the user decide.

I'm planning a **one_for_rule_them_all** function (as you called it :laughing: ) with all the possible functionality and create some *shorthand* functions (`daily_metrics`, `monthly_metrics`, `predawn_metrics` and so on...). The advantage of having the **one_for_rule_them_all** is that it will let the users provide their own custom summarising functions, quantiles, middday and predawn times, nighttime method, etc... giving the end user extra functionality that we don't have to think about.

**Comment by rafapoyatos** [comment]
@MalditoBarbudo @vflo 

I agree. Another metrics that we could try to implement is the diurnal centroid and diurnal centroid relative to radiation, following Jake's paper:

https://www.biogeosciences-discuss.net/bg-2017-152/

It's a relatively simple calculation, and he has Python code available https://github.com/jnelson18/FluxnetTools/blob/master/FileS3.py

but one thing to bear in mind is that they work with 30-min data, and our timestep is variable, and more worryingly, it can change within the same dataset. I wouldn't list it as a priority right now, but it's something to consider for the sub-daily analyses...

**Comment by MalditoBarbudo** [comment]
@rafapoyatos @vflo 
Ok, I have been reading the python code and it can be implemented, but the changing timesteps will be challenging...

**Comment by rafapoyatos** [comment]
@MalditoBarbudo @vflo 
We can simply restrict this metrics to datasets with homogeneous timestep

**Comment by MalditoBarbudo** [comment]
All implemented in devel brach of package with the following NOTES:

- nighttime division is only implemented by hours at the moment. It returns metrics for each day and each nigth (the latter spans DOY and DOY-1)

- diurnal centroid metric is implemented assuming constant timestep (it takes the values for the day and the number of intervals and performs the calculations). It is easier to give the user a warning about the possible wrong values generated that checking all time if the timestep is correct.

- quantiles. User can provide a vector of probabilities (i.e. `probs = c(0.95, 0.99)`) of any length => 1 and the function will generate a column in the summary for each quantile.

- `daily_metrics(SITE_OBJECT)` and `monthly_metrics(SITE_OBJECT)` return by default a list with the environmental and the sapflow metrics for general (all data), predawn and midday. I left out nighttime by default as it can be heavy in large datasets and I think it's better to have a dedicated wrapper function for that (`nightime_metrics(SITE_OBJECT)`, yet to create)

- There is a master function (`sfn_metrics`) which can be used to perform custom and more complex metrics.

As an example, combining all code availbale at the moment, if you want to work with all mediterranean sites, this will be something like:
```
library(tidyverse)
library(sapfluxnetr)

res <- filter_by_var(si_biome == 'Mediterranean', folder = 'Data') %>%
  read_sfn_data(solar = TRUE) %>%
  daily_metrics(pd_start = 4, pd_end = 6, md_start = 13, md_end = 15)
```
 This will create a list of all mediterranean sites containing the summaries (general, predawn and midday) for environmental and sapflow data:

```
$ SITE_ONE
    $ sapf
        $ sapf_gen
        $ sapf_pd
        $ sapf_md
    $ env
        $ env_gen
        $ env_pd
        $ env_md
$ SITE_TWO
...
```
This format allows for easy combining the sapf/env data for all sites, or filtering by sites to remove, or do whatever...

Filter can be as complex as the user want:

```
filter_by_var(
  si_biome == 'Mediterranean',
  pl_saw_area > 23,
  folder = 'Data'
)
```

will return the names of sites with mediterranean biome and at least one tree with sapwood area higher than 23. In summary *any metadata variable* can be used to filter the sites.

**Comment by MalditoBarbudo** [comment]
Now in master
