### ISSUE TITLE
"acummulated" metric for precipitation?

### ISSUE THREAD

**Issue by MalditoBarbudo** [sapfluxnet/sapfluxnetr#11]
Mean maybe is not the optimal metric to compare precipitation with any other variable. Also, could it be useful for sapflow?

**Comment by rafapoyatos** [comment]
@MalditoBarbudo Ideally, summing precipitation amounts should be the standard behaviour of a precip metrics (over 24 h, daytime, or whichever the aggregation period).
I use a temporary workaround by using `env_timestep` to convert mean precip (from daily metrics) to mean daily precipitation per timestep and then aggregate to daily values.

**Comment by MalditoBarbudo** [comment]
Ok, I will see how to implement this to avoid the workaround and make things easier.

**Comment by MalditoBarbudo** [comment]
**DONE** in `devel` branch.
The solution is a little *hacky*, as we calculate an accumulated metric for all variables (is a `sum`, so no overhead there) and we remove them from the results in `summarise_metrics` function.
This means that the name `accumulated` is now a reserved function name in the funs argument of `sfn_metrics` as well as `centroid` (If the user supply custom aggregation functions with those names, well....  *there will be dragons* :dragon: :dragon_face:)
