### ISSUE TITLE
NA in si_code using "metrics_tidyfier()" on AUS_MAR_HSW_HIG

### ISSUE THREAD

**Issue by vflo** [sapfluxnet/sapfluxnetr#14]
I have run the following code:
```
read_sfn_data(.x,
                    folder=folder_plant) %>%
        sfn_metrics(period = 'daily', 
                    .funs = sapfluxnetr:::.fixed_metrics_funs(0.95, FALSE)[c(1,3)],
                    solar = TRUE, 
                    interval = 'general') %>% 
        metrics_tidyfier( metadata = sfn_metadata,
                          interval = 'general' )
```
 where .x is "AUS_MAR_HSW_HIG" character string. I got the result bellow:

![Captura de pantalla de 2019-03-25 21-51-02](https://user-images.githubusercontent.com/12745260/54953426-7cb53200-4f48-11e9-968c-45e8aeda3fa7.png)

**Comment by MalditoBarbudo** [comment]
Tree names in this dataset are wrong:

site name: AUS_MAR_HSW_HIG
tree names: AUS_MAR_HSW (the lack the last part of the code)

This makes the si_code col to be empty when analysising this site isolated. It works when is processed in `sfn_data_multi` object, but with incorrect plant names

**Comment by MalditoBarbudo** [comment]
There is no fix until the next version of the database, sorry. But there is a workaround for you now:

1. get the sapf data from the site and modify the names of the trees to the correct ones
2. get the plant metadata from the site and modify the pl_code with the correct ones
3. assign the corrected slots to the object
4. save the object in the RData/plant
5. regenerate the metadata cache
6. you are good to go:

```
bad_site <- read_sfn_data('AUS_MAR_HSW_HIG', folder)

good_sapf_data <- bad_site %>%
  get_sapf_data() %>%
  select(
    AUS_MAR_HSW_HIG_Eob_Js_1 = AUS_MAR_HSW_Eob_Js_1,
    AUS_MAR_HSW_HIG_Eob_Js_2 = AUS_MAR_HSW_Eob_Js_2,
    AUS_MAR_HSW_HIG_Eob_Js_3 = AUS_MAR_HSW_Eob_Js_3,
    AUS_MAR_HSW_HIG_Ecy_Js_4 = AUS_MAR_HSW_Ecy_Js_4
  )

good_plant_md <- bad_site %>%
  get_plant_md() %>%
  mutate(
    pl_code = stringr::str_replace(pl_code, 'AUS_MAR_HSW_', 'AUS_MAR_HSW_HIG_')
  )

AUS_MAR_HSW_HIG <- bad_site
get_sapf_data(AUS_MAR_HSW_HIG) <- good_sapf_data
get_plant_md(AUS_MAR_HSW_HIG) <- good_plant_md

save(AUS_MAR_HSW_HIG, file = file.path(folder, 'AUS_MAR_HSW_HIG.RData'))
sfn_metadata <- read_sfn_metadata(folder, .write_cache = TRUE)

read_sfn_data('AUS_MAR_HSW_HIG', folder=folder) %>%
  sfn_metrics(period = 'daily', .funs = sapfluxnetr:::.fixed_metrics_funs(0.95, FALSE)[c(1,3)], solar = TRUE, interval = 'general') %>%
  metrics_tidyfier( metadata = sfn_metadata, interval = 'general' )
```

**Comment by MalditoBarbudo** [comment]
I forgot,
You will need to do this also for sapwood and leaf unit levels, as they (if exist) will have also wrong plant names

**Comment by MalditoBarbudo** [comment]
See https://gist.github.com/MalditoBarbudo/d11a7b66989e03182ff97008f2c808a2
for a complete solution for known `data-bugs` in SAPFLUXNET data.

**Comment by MalditoBarbudo** [comment]
Fixed in the new database version
