### ISSUE TITLE
Functions created but not included in main_script.R

### ISSUE THREAD

**Issue by guillembagaria** [sapfluxnet/sapfluxnetr#21]
Here is a list of functions that were created and tested, but not included yet in the main script.
# **Functions to include in main_script.R**

(Checked boxes indicate inclusion in the main script)
- [ ] **`qc_rad_conversion`**
- [x] **`qc_soil_texture`**
- [ ] **`qc_ext_radiation`**
- [x] **`qc_get_biome`**: Once added to the main script (it will append MAT and MAP to site_md), the biome plot in sfn_monitor will not need to fetch climate data out of WorldClim each time.

**Comment by MalditoBarbudo** [comment]
`qc_soil_texture` and `qc_get_biome` included in the QC flow.
`qc_rad_conversion` and `qc_ext_radiation` will be included in the **Level 2** workflow, as they are data filling or data conversion functions.
