### ISSUE TITLE
Parallelization with furrr and future

### ISSUE THREAD

**Issue by MalditoBarbudo** [sapfluxnet/sapfluxnetr#7]
With `furrr` package available in an stable form, and the mature state of `future` package (rstudio backed, included by default in `shiny` to achieve asynchronous execution, a well documentation of features and use-cases...) it may be the time to adapt `sapfluxnetr` to the new times :wink: 
The idea is to allow the user to opt-in to parallelize the metrics and the "tidyfication" when using a sfn_data_multi as starting point.

Pros:
  - When analyzing more than five sites the time benefit is expected to be considerable

Cons:
  - When analyzing less than five sites, there is no time benefit, hence the posibbility of opt-in or opt-out
  - Big sites still are a bottleneck, but at least other sites are running at the same time
  - **Memory**. There is a possibility that this approach increases the memory used in the process.

Planning:

  1. Implement the `furrr::future_map*` calls and test that there is no changes in results compared to the old behaviour (none must be expected)
  2. Benchmark the time and memory used when processing the biggest dataset collection possible (in my system, with 32Gb of RAM, I don't think that I will be able to test this with the 202 sites, but at least a 100 sites subset will be a good test)
  3. Decision taking. If there is a substantial adventage in time and/or memory and no drawbacks, this implementation will be merged in the devel branch. If not, well, I will learn a lot :grin: 

Work on this will be commited to the `furrr_implementation` branch

**Comment by MalditoBarbudo** [comment]
Commit 7ee56ab7137b4e646a65eec757b2be969498709a in `furrr_implementation` branch includes a new logic for `metrics_tidyfier` which is more efficient (from ~2G to ~500M) and faster (from 7 to 1 second, see image attached) in a 10 sites test suite.
The *funny* thing is that this was achieved by changing the order of some steps (and thus substituting a big big `dplyr::spread` step by several but smaller `dplyr::spread` steps), but using exactly the same functions as before.


![tidyfier_alt_speed](https://user-images.githubusercontent.com/4775311/44301422-b79e1a00-a316-11e8-95b7-63e14392b946.png)

**Comment by MalditoBarbudo** [comment]
### UPDATE:
Inspecting the `sfn_metrics` process, the bottleneck here is located in the `summarise_by_period` function, in the `dplyr::summarise_all` step. This is due to metrics calculated by default:

1. mean
2. sd
3. n
4. coverage
5. quantile 95
6. quantile 99
7. max
8. max_time
9. min
10. min_time
11. centroid

And mainly, in those, the `stats::quantile` metrics sum more than 60% of the time and ~ 30% of the memory consumed in the process (remember, we calculate two quantiles). In tests, reducing the metrics calculated to:

1. mean
2. sd
3. coverage
4. quantile 95
5. centroid

speed up the process considerably and reduces the memory used in processing 32 sites (including *tidyfying*) to ~ 2GB (the total memory use is 7G, but the default garbage collection behaviour in R frees memory for the OS to use when needed, so the *real* memory consumed never rises above 2.5G). This is promising, as I can not do anything more "*code-oriented*" to reduce the memory use (the process is simple, neat and 99% of the time is located in the `dplyr::sumarise_all` step), so we need to reduce to max five metrics including only one quantile.

So, @rafapoyatos @vflo, you need to decide which quantile you want, as well as the other metrics to calculate (max to five).

#### NOTE:
The reduction of metrics will impact positively to `metrics_tidifyer`, as the columns in the result obect are reduced, lowering the memory load in the `tidyr::spread` steps.

**Comment by MalditoBarbudo** [comment]
## UPDATE:

Without parallelization, all the `sapwood` level sites (168 sites) can perform the complete daily metrics process at one time without collapsing the system (in my laptop):

```r
folder <- '../sapfluxnet_db/0.0.3/sapwood/'
sites <- list.files(folder, pattern = '.RData') %>%
    stringr::str_remove('.RData')
metadata <- read_sfn_metadata(folder, .write_cache = FALSE)
res <- read_sfn_data(sites, folder) %>%
    daily_metrics(tidy = TRUE, metadata = metadata)
```

Doing this, 10-12 minutes are spent and a total of 9.5Gb of RAM memory (most of it liberated, the real deal are 2.4Gb after the process is done) is used. So this is a huge improvement compared to the `devel` branch, meaning that in powerful system configurations (16-32 Gb RAM) like the server one this can be done in one step.

*Edited: typo*

**Comment by vflo** [comment]
@MalditoBarbudo the 5 metrics you're suggesting are fine for me. The other metrics could be suggested in the package and could they be calculated individually if the user needs them?

**Comment by MalditoBarbudo** [comment]
@vflo Yeah, I was thinking the same, in fact they already can. I mean, the users have the possibility to provide their own metric functions when using `sfn_metrics` directly, so if they want daily metrics with only the mean, min, and max they can do it directly

**Comment by MalditoBarbudo** [comment]
### UPDATE:

#### `sfn_metrics`
Implementing `furrr::future_map` results in all the process consuming a max of ~20Gb (at the end 2.4Gb as in the default mode without parallelization, beacuse the final object is of that size). The advantage is that the complete process is ~290 seconds (~5 minutes), so it is worthy. It must be noted that this results are for my system, 8 cores and 32Gb RAM. This is important, because with 4 cores for example, the time will rise but the memory will be reduced.

#### `metrics_tidyfier`
Implementing `furrr::future_map` in this function does not improve the process, in fact, it is counter-productive. The only place to locate the future calls are in the sapflow data modifications (`sapflow_tidy` function) and this results in a lot of data moving between the spawned R processes, which is one of the cases when the `multiprocess` approach fails to be more efficient than the `sequential` one.

#### Conclusion
`furrr::future_map` will be implemented in sfn_metrics, and following the `future` package philosophy, the option to be parallelized will must be declared by the user using the `future::plan` function. So, this:

```r
  folder <- '../sapfluxnet_db/0.0.3/sapwood/'
  sites <- list.files(folder, pattern = '.RData') %>%
    stringr::str_remove('.RData')
  metadata <- read_sfn_metadata(folder, .write_cache = FALSE)
  res <- read_sfn_data(sites, folder) %>%
    daily_metrics(tidy = TRUE, metadata = metadata)
```
will result in a sequential (not parallelized) execution, but this:

```r
library(future)

# this is beacuse the default max size to send to one process
# is 500Mb, but in our database this limit is easily exceeded.
# With this we set the max limit to 1Gb
options('future.globals.maxSize' = 1014*1024^2)

# We set the future plan to multiprocess, as it uses multicore in
# linux and multisession in Windows, automatically
plan('multiprocess')

# the tidy metrics (exactly as before)
  folder <- '../sapfluxnet_db/0.0.3/sapwood/'
  sites <- list.files(folder, pattern = '.RData') %>%
    stringr::str_remove('.RData')
  metadata <- read_sfn_metadata(folder, .write_cache = FALSE)
  res <- read_sfn_data(sites, folder) %>%
    daily_metrics(tidy = TRUE, metadata = metadata)
``` 

will result in a parallelized execution.

#### Beyond
These results make possible to execute this in the server for all sites in one time, opening the posibility of **automated metrics database builds**. This is, we can build a SQL db with the precalculated metrics (daily, monthly, predawn...) tables, for all sites for a fast and quick use (internal until the embargo is lifted, and completly open after that), and update it automatically :tada: :tada:

**Comment by rafapoyatos** [comment]
@MalditoBarbudo @vflo 
This is great progress! About some earlier discussions on selecting the metrics, for the quantile, an option could be that the user selects which one wants to calculate (95%, 99%, etc.). I don't know if that's feasible, but if it isn't, a safer bet would be to leave 95% by default...

**Comment by MalditoBarbudo** [comment]
@rafapoyatos I knew you will say that :stuck_out_tongue_winking_eye: and it's already implemented. Users can give all the probabilities they want and the quantiles will be calculated (at memory and time cost), but if nothing is specified, only the 95% quantile is calculated by default.

**Comment by MalditoBarbudo** [comment]
## FINAL UPDATE
This has been implemented in the `furrr_implementation` branch, along with some other changes:

##### sapfluxnetr 0.0.4.9000 NEWS (in `furrr_implementation` branch)

* Added helper function `sfn_sites_in_folder` to list the site codes in a folder
* Deprecated `filter_by_var`, substituted by `filter_sites_by_md`
* **Implementation of furrr::future_map** in `sfn_metrics`. After some
  benchmarking, the benefits in time are solid, so now the user has the ability
  to perform the metrics in parallel.
* New logic with performance improvements for metrics_tidyfier (introducing the
  .sapflow_tidy internal helper function)
* Added get methods for sfn_data_multi class objects
* Fixed bug in metrics function that created min and max time variables as double
  instead of POSIXct in sites with NAs in the first day of measures
* Now species metadata variables are returned individually instead of in a list

This branch will be merged with devel and the issue will be closed
